import { createHash } from "node:crypto";
import Decimal from "decimal.js";
import { AI_PROVIDER_PROMPT_VERSION, researchHypothesisOutputSchema } from "./hypothesis-schema";
import type { AIProvider, AIProviderResult, ResearchAgentPromptInput } from "./types";

/**
 * Fully deterministic, zero-network AIProvider, the default whenever
 * ANTHROPIC_API_KEY is unset, and always used by automated tests/CI. Seeds
 * its output from a hash of the input so identical input always produces
 * byte-identical output, satisfying the "deterministic mock AI mode"
 * requirement without ever making the mock's hypothesis content
 * meaningful, it is a structural stand-in for tests and dry runs, never a
 * real research conclusion.
 */
export class MockAIProvider implements AIProvider {
  readonly type = "MOCK" as const;

  async generateResearchHypothesis(
    input: ResearchAgentPromptInput,
  ): Promise<AIProviderResult<import("./hypothesis-schema").ResearchHypothesisOutput>> {
    const seed = createHash("sha256").update(JSON.stringify(input.summary)).digest("hex").slice(0, 8);

    const rawOutput = {
      title: `Mock hypothesis ${seed}`,
      statement: `Deterministic mock statement generated from input hash ${seed}. Not a real research conclusion.`,
      rationale: "Generated by MockAIProvider for testing. No real data interpretation occurred.",
      confidence: "LOW" as const,
      proposedStrategyDefinition: {
        version: "1.0.0" as const,
        direction: "LONG" as const,
        entryRules: [{ type: "EMA_CROSS_ABOVE" as const, fastPeriod: 20, slowPeriod: 50 }],
        atrPeriod: 14,
        stopAtrMultiplier: 1,
        targetAtrMultiplier: 2,
      },
    };

    const output = researchHypothesisOutputSchema.parse(rawOutput);
    const rawResponse = JSON.stringify(rawOutput);

    return {
      output,
      rawResponse,
      promptVersion: AI_PROVIDER_PROMPT_VERSION,
      model: "mock-v1",
      tokensInput: JSON.stringify(input.summary).length,
      tokensOutput: rawResponse.length,
      costUsd: new Decimal(0),
    };
  }
}
